name: Deploy Pre-production to Render

on:
    push:
      branches:
        - main

jobs:

  deploy:
    name: Deploy Pre-production to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_PREPROD_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
